[package]
name = "upgradeability"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "27.0.1" }
common_error = { path = "../common_error" }

[dev-dependencies]
soroban-sdk = { version = "27.0.1", features = ["testutils"] }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
testutils = ["soroban-sdk/testutils"]
